### ISSUE TITLE
Godot 4.0 support?

### ISSUE THREAD

**Issue by TicklesTheBrain** [issork/gift#13]
Hey, great add-on. Is this compatible with Godot 4.0? If not, are you planning on updating it?

Thanks.

**Comment by issork** [comment]
Yes, this will be updated to Godot 4.0, currently it is not compatible.

**Comment by ColeDingo** [comment]
Has there been any progress on this? I've been trying to port this myself and I'm not having too much luck.

**Comment by issork** [comment]
I've been busy with my own game, this will be rewritten for Godot 4 on the next weekend :)

**Comment by ColeDingo** [comment]
Thank you!!

if it's not any trouble would you be willing to explain what you change? I don't fully understand how websockets work and even less so the way they changed from Godot 3.5 to 4, It looks like WebSocketClient is completely gone.

**Comment by issork** [comment]
Done, please test if everything works properly <3

**Comment by ColeDingo** [comment]
Looks like it's working, thank you!! 🙇 🙇 🙇
