### ISSUE TITLE
HTTPClient polled multiple times

### ISSUE THREAD

**Issue by SnipFernandez** [issork/gift#15]
I am trying to use the library and that it comes by default exporting to html5 with godot 3.5, but when I receive a chat message, it goes into a loop with the following error:

tmp_js_export.js:369 WARNING: HTTPClient polled multiple times in one frame, but request cannot progress more than once per frame on the HTML5 platform.

tmp_js_export.js:369    at: poll (platform/javascript/http_client_javascript.cpp:270) - HTTPClient polled multiple times in one frame, but request cannot progress more than once per frame on the HTML5 platform.

and from there everything stops working.

**Comment by issork** [comment]
This is because threads are not supported on the HTML5 platform. I will rewrite this to use the HTTPRequest node instead with Godot 4.0.

**Comment by SnipFernandez** [comment]
That's right, I was researching and saw what that was, thanks :)

**Comment by SnipFernandez** [comment]
I close the thread, because I understand that it will be solved in godot 4
