### ISSUE TITLE
Bits, subs, alerts and channel point integration

### ISSUE THREAD

**Issue by Fourgees** [issork/gift#17]
Is there a way or a roadmap for adding alerts for subs, bits and channel points?

**Comment by issork** [comment]
Yes, this is coming after #16 :)
Currently you'd have to connect to Twitch with a seperate websocket yourself, as the events are fired from a different API at wss://pubsub-edge.twitch.tv

More details here; https://dev.twitch.tv/docs/pubsub/

**Comment by issork** [comment]
Done, testing would be appreciated <3
