### ISSUE TITLE
Invalid type in function 'connect_to_eventsub' in base 'Node ()'. Cannot convert argument 1 from Nil to String.

### ISSUE THREAD

**Issue by Fourgees** [issork/gift#18]
Here is the error I got after running the gift example project for awhile:

Invalid type in function 'connect_to_eventsub' in base 'Node ()'. Cannot convert argument 1 from Nil to String.

This was at line 351 in gift_node.gd - connect_to_eventsub(await(events_reconnect))

I also get a bunch of empty print statements { }  over and over as it runs but this might be intentional.

**Comment by issork** [comment]
The print was an overlook on my side, it printed the brackets on every keepalive message. This should now be fixed, I had a remaining reconnect signal that emitted without a value for the reconnect url.
