### ISSUE TITLE
Check if joining a channel is successful (or get a list of channel)

### ISSUE THREAD

**Issue by HephepTeam** [issork/gift#27]
Hello, I have a game and I want the user to input account name, secret and channel for the game to join, and I want to check thoses parameters against invalid parameters, and I didn't see anything about the channel, I'm not really familiar to Twitch and I'm not sure if this is relevant but I don't want the user to just wait for ever, thinking the game is busy joining channel even if it's not.

**Comment by issork** [comment]
I'm sorry, completely missed this issue. This is possible by checking if the channel_data_received signal is emitted - it is only emitted once the initial channel tags have been sent.

I'm currently rewriting the entire plugin which will make everything much easier.
