### ISSUE TITLE
Hangs on Token Request

### ISSUE THREAD

**Issue by JFurness1** [issork/gift#34]
I have created the `auth.txt` file and the `Example.tscn` pops up my browser to a Twitch redirect at `https://id.twitch.tv/oauth2/authorize?response_type=code&client_id=REDACTED&redirect_uri=http://localhost:18297&scope=chat%3Aedit%20chat%3Aread%20moderator%3Aread%3Afollowers` which continues to  `https://twitchtokengenerator.com/?error=redirect_mismatch&error_description=Parameter+redirect_uri+does+not+match+registered+URI`, which doesn't look a happy URL. 

From here, I can't tell if it's me making a mistake, or something else wrong. The web page asks me if I want to make a bot or custom token as usual. I see no interaction on the page that logs the example project bot in. The print log shows `Waiting for user to login.` and will go no further.

Apologies if this is a trivial mistake my end, I'm a little stuck at how to proceed.

**Comment by issork** [comment]
Your redirect URL in your Twitch developer console has to be exactly `http://localhost:18297`

![image](https://github.com/issork/gift/assets/12477395/5bcd1206-bcf3-4ac3-a0af-e0076047f0ae)

If that does not work, let me know.

**Comment by JFurness1** [comment]
Got it. Thanks for the quick reply!
That sorted the problem. Thanks for helping me out. 

It might be nice for simpletons like myself to expand the comments on lines 20 and 21 to briefly cover that step and prompt it if the scene appears to be hanging. I now understand the message in the README about this step, but it wasn't clear to me from that alone. Being poked towards the developer console was useful for me.

Thanks again!
