### ISSUE TITLE
Dictionary key error if invalid secret is used after successful login

### ISSUE THREAD

**Issue by JFurness1** [issork/gift#35]
I had GIFT up and running. Great add-on, thanks for all your work!

I accidentally committed my secret to my repo (despite making an auth file to avoid that 😒) so I created a new secret at dev.twitch.tv and updated the secret in the auth file.

Now attempting to connect I receive a `403: Invalid client secret` response and the add-on crashes at line `174` in `gift_node.gd`.

![image](https://github.com/issork/gift/assets/6610047/311a3ed2-6a0a-49ad-b353-8c953bd692f8)

**Comment by issork** [comment]
Try deleting the file located at `user://gift/auth/user_token` and let me know if that fixes it - will fix this problem in a future update if it does.

**Comment by JFurness1** [comment]
No fix from that.

I think the problem is that when the 403 is returned the token dictionary has only two entries, neither of which is `"access token"`.
